// lib/resend.js
//
// Sends the alert as a formatted email via Resend.

export async function sendAlertEmail({ to, symbol, triggerDetail, explanation }) {
  const res = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${process.env.RESEND_API_KEY}`,
    },
    body: JSON.stringify({
      from: process.env.ALERT_FROM_EMAIL || "alerts@yourdomain.com",
      to,
      subject: `⚡ Alert: ${symbol} — ${triggerDetail}`,
      html: `
        <div style="font-family: sans-serif; max-width: 480px;">
          <h2 style="margin-bottom: 4px;">${symbol} Alert</h2>
          <p style="color:#555; margin-top:0;">${triggerDetail}</p>
          <p>${explanation}</p>
          <hr style="border:none;border-top:1px solid #eee;" />
          <p style="color:#999; font-size:12px;">
            Generated by Alert &amp; Analysis Agent — built on Binance Agent OS.
          </p>
        </div>
      `,
    }),
  });

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`Resend error ${res.status}: ${body}`);
  }

  return res.json();
}
